In [1]:
import numpy as np

# Creating the 1D NumPy array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# Inspecting properties
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)


Shape: (7,)
Data type: float64
Number of elements: 7


In [3]:
import numpy as np

# Week 1 temperatures in Celsius
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# Convert Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32

# Find max, min, mean
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Temperatures in Fahrenheit:", temperatures_f)
print("Maximum temperature (°C):", max_temp)
print("Minimum temperature (°C):", min_temp)
print("Mean temperature (°C):", mean_temp)


Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature (°C): 26.1
Minimum temperature (°C): 20.8
Mean temperature (°C): 23.542857142857144


In [4]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

# First three days (indices 0,1,2)
first_three_days = temperatures_w1[:3]

# Weekend (last two days → indices 5,6)
weekend = temperatures_w1[-2:]

# Middle three days (indices 2,3,4)
middle_three_days = temperatures_w1[2:5]

print("First three days:", first_three_days)
print("Weekend:", weekend)
print("Middle three days:", middle_three_days)


First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [5]:
import numpy as np

# Week 1 and Week 2 temperatures
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print(temperatures)


[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [6]:
import numpy as np

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

# Inspect properties
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

# Extract each week
week1 = temperatures[0]   # Row 1
week2 = temperatures[1]   # Row 2

# Extract weekends (last two days for both weeks → columns 5 and 6)
weekends = temperatures[:, -2:]

print("Week 1:", week1)
print("Week 2:", week2)
print("Weekends (both weeks):\n", weekends)


Shape: (2, 7)
Data type: float64
Total number of elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekends (both weeks):
 [[24.8 21.9]
 [22.8 20.1]]


In [7]:
import pandas as pd

# Creating the Pandas Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [8]:
import pandas as pd

# Creating the Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

# 1. Integer index position → 1st rank student (index 0)
first_rank = marks[0]

# 2. loc accessor → top 3 ranks by labels
top3_loc = marks.loc[['Rank1', 'Rank2', 'Rank3']]

# 3. iloc accessor → 3rd rank student (index 2)
third_rank = marks.iloc[2]

# 4. Boolean mask → marks greater than 90
greater_than_90 = marks[marks > 90]

print("Mark of 1st rank (by position):", first_rank)
print("Top 3 ranks (loc):\n", top3_loc)
print("Mark of 3rd rank (iloc):", third_rank)
print("Ranks with marks > 90:\n", greater_than_90)


Mark of 1st rank (by position): 95
Top 3 ranks (loc):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
Mark of 3rd rank (iloc): 89
Ranks with marks > 90:
 Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_3381/2036966350.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  first_rank = marks[0]


In [9]:
import pandas as pd

# Original Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

# 1. Modify the mark of the 1st rank student to 100
marks['Rank1'] = 100

# 2. Remove the entry for the last rank (Rank5)
marks = marks.drop('Rank5')

# 3. Compute CGPA by dividing each mark by 10
cgpa = marks / 10

print("Updated Marks:\n", marks)
print("\nCGPA:\n", cgpa)


Updated Marks:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [10]:
import pandas as pd

# Creating the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [11]:
import pandas as pd

# Creating the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# 1. Display DataFrame and basic info
print(transactions.head())       # First 5 rows
print(transactions.tail())       # Last 5 rows
print("Shape:", transactions.shape)
print("Column names:", transactions.columns.tolist())
print("Data types:\n", transactions.dtypes)

# 2. Display only ProductCategory and Amount columns
print(transactions[['ProductCategory', 'Amount']])

# 3. Retrieve last 3 columns using iloc
print(transactions.iloc[:, -3:])

# 4. Filter rows where Region is 'North' and Amount > 200
filtered = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print(filtered)

# 5. Value counts for ProductCategory
print(transactions['ProductCategory'].value_counts())

# 6. Unique values in Region
print(transactions['Region'].unique())

# 7. Group by Region and find mean amount
print(transactions.groupby('Region')['Amount'].mean())


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Shape: (10, 4)
Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
Data types:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300

In [12]:
import pandas as pd

# Original DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# 1. Modify the 'Amount' for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

# 2. Add a new column 'Discount' (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10

# 3. Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

# 4. Delete the 'Discount' column
transactions = transactions.drop(columns=['Discount'])

print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
